apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: httpd-service
spec:
  selector:
    env: developer
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
  selector:
    app: httpd
    tier: frontend
  type: LoadBalancer